# Configurations for various database connections used in specs
#dummy config for use when a connection to an actual database is not necessary for the spec
sqlite:
  database: 'tmp/sqlite.sqlite3'
  adapter: sqlite
